LineageOS-23-kebab:
  kernel:
    - git clone --depth=1 https://github.com/LineageOS/android_kernel_oneplus_sm8250.git -b lineage-23.0
  clang:
    - mkdir -p clang && wget -qO- "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz" | tar -C clang -zxf -
  config:
    - make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu- LD=ld.lld LLVM=1 vendor/kona-perf_defconfig vendor/oplus.config
  build:
    - make -j$(nproc --all) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu- LD=ld.lld LLVM=1
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - kebab
  kernelSU:
    - next-legacy

LineageOS-23.2-kebab:
  kernel:
    - git clone --depth=1 https://github.com/LineageOS/android_kernel_oneplus_sm8250.git -b lineage-23.2
  clang:
    - mkdir -p clang && wget -qO- "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz" | tar -C clang -zxf -
  config:
    - make O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 vendor/kona-perf_defconfig vendor/oplus.config
  build:
    - make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - kebab
  kernelSU:
    - next-legacy

Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status

# KernelSU Next integration commands
# next-stable: uses the stable branch of KernelSU-Next
# next-latest: uses the latest release tag of KernelSU-Next
# next-legacy: uses the legacy branch for older kernels (4.x)
# next-pin: uses a pinned version from ksu_version.txt
KernelSU:
  version:
    next-stable:
      - curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s stable
    next-latest:
      - curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
    next-legacy:
      - curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy
    next-pin:
      - curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s kernelsu-version

AnyKernel3:
  version:
    kebab:
      - git clone https://github.com/osm0sis/AnyKernel3.git -b master
